#ifndef ROOT_RVersion
#define ROOT_RVersion

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if ROOT_VERSION_CODE >= ROOT_VERSION(2,23,4)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define ROOT_RELEASE "5.17/100"
#define ROOT_RELEASE_DATE "Nov 4 2007"
#define ROOT_RELEASE_TIME "08:00:00"
#define ROOT_SVN_REVISION 20643
#define ROOT_SVN_BRANCH "branches/dev/proof-tags/v5-17-05-PROOF-00"
#define ROOT_VERSION_CODE 332132
#define ROOT_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#endif
