#ifndef ROOT_RVersion
#define ROOT_RVersion

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if ROOT_VERSION_CODE >= ROOT_VERSION(2,23,4)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define ROOT_RELEASE "5.21/101"
#define ROOT_RELEASE_DATE "Dec 05 2008"
#define ROOT_RELEASE_TIME "09:40:53"
#define ROOT_SVN_REVISION 26757
#define ROOT_SVN_BRANCH "branches/dev/proof-tags/v5-21-07-PROOF-00"
#define ROOT_VERSION_CODE 333161
#define ROOT_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#endif
