#! /bin/bash
# script to generate a standalone unit test for root daily tests
# Author: Eckhard v. Toerne, Dec 2010
# 
outfile=stressTMVA.cxx
cat <<EOF >$outfile
// 
// this stress test for TMVA is a shorter version of the extended TMVA testsuite 
// generated by script tmvaValidation/testsuite/RootTest/buildRootTest.sh
//
// Eckhard von Toerne, Dec 2010
//
/* if working, it creates output like this:

******************************************************************                                                                            
* TMVA - S T R E S S and U N I T test suite (FAST)                                                                                            
******************************************************************                                                                            
Event [107/107]..................................................OK     
VariableInfo [31/31].............................................OK 
DataSetInfo [20/20]..............................................OK   
DataSet [15/15]..................................................OK 
Factory [11/11]..................................................OK
Reader [2/2].....................................................OK
CutsGA [3/3].....................................................OK
LikelihoodD [4/4]................................................OK
PDERS [4/4]......................................................OK
PDEFoam [4/4]....................................................OK
KNN [4/4]........................................................OK
Fisher [4/4].....................................................OK
BoostedFisher [4/4]..............................................OK
LD [4/4].........................................................OK
MLP [4/4]........................................................OK
MLPBFGS [4/4]....................................................OK
SVM [4/4]........................................................OK
BDTG [4/4].......................................................OK
BDT [4/4]........................................................OK
Regression_LD [4/4]..............................................OK
Regression_MLPBFGSN [4/4]........................................OK
Regression_BDTG2 [4/4]...........................................OK
Event [107/107]..................................................OK
VariableInfo [31/31].............................................OK
DataSetInfo [20/20]..............................................OK
DataSet [15/15]..................................................OK
Factory [11/11]..................................................OK
Reader [2/2].....................................................OK
CutsGA [3/3].....................................................OK
LikelihoodD [4/4]................................................OK
PDERS [4/4]......................................................OK
PDEFoam [4/4]....................................................OK
KNN [4/4]........................................................OK
Fisher [4/4].....................................................OK
BoostedFisher [4/4]..............................................OK
LD [4/4].........................................................OK
MLP [4/4]........................................................OK
MLPBFGS [4/4]....................................................OK
SVM [4/4]........................................................OK
BDTG [4/4].......................................................OK
BDT [4/4]........................................................OK
Regression_LD [4/4]..............................................OK
Regression_MLPBFGSN [4/4]........................................OK
Regression_BDTG2 [4/4]...........................................OK
******************************************************************
*  SYS: Linux linux-7p93 2.6.27.7-9-default #1 SMP 2008-12-04 18:10:
*  SYS: "openSUSE 11.1 (x86_64)"
******************************************************************
*  CPUTIME   =  90.2   *  Root5.27/07   20100929/1318
******************************************************************
*/
EOF
for i in UnitTest UnitTestSuite utDataSetInfo utDataSet utEvent utReader utFactory utVariableInfo MethodUnitTestWithROCLimits RegressionUnitTestWithDeviation MethodUnitTestWithComplexData; do
    echo "// including file tmvaut/$i.h" >>$outfile
    cat ../tmvaut/$i.h >> $outfile
    echo "// including file tmvaut/$i.cxx" >>$outfile
    cat ../tmvaut/$i.cxx >> $outfile
done
echo "// including file stressTMVA.cxx" >> $outfile
cat ../stressTMVA.cxx >> $outfile

for ihead in UnitTest UnitTestSuite utDataSetInfo utDataSet utEvent utReader utFactory utVariableInfo MethodUnitTestWithROCLimits RegressionUnitTestWithDeviation MethodUnitTestWithComplexData; do
    cat $outfile | sed "s/#include \"$ihead.h\"//g" |  sed "s/#include \"tmvaut\/$ihead.h\"//g" > temp.cxx
    mv temp.cxx $outfile
done
