# Module.mk for spectrumpainter module
# Copyright (c) 2000 Rene Brun and Fons Rademakers
#
# Author: Olivier Couet, 27/11/2006

MODDIR       := spectrumpainter
MODDIRS      := $(MODDIR)/src
MODDIRI      := $(MODDIR)/inc

SPECTRUMPAINTERDIR  := $(MODDIR)
SPECTRUMPAINTERDIRS := $(SPECTRUMPAINTERDIR)/src
SPECTRUMPAINTERDIRI := $(SPECTRUMPAINTERDIR)/inc

##### libSpectrumPainter #####
SPECTRUMPAINTERL  := $(MODDIRI)/LinkDef.h
SPECTRUMPAINTERDS := $(MODDIRS)/G__Spectrum2Painter.cxx
SPECTRUMPAINTERDO := $(SPECTRUMPAINTERDS:.cxx=.o)
SPECTRUMPAINTERDH := $(SPECTRUMPAINTERDS:.cxx=.h)

#LF
SPECTRUMPAINTERTMPDS    := $(MODDIRS)/G__Spectrum2PainterTmp.cxx
SPECTRUMPAINTERTMPDO    := $(SPECTRUMPAINTERTMPDS:.cxx=.o)
SPECTRUMPAINTERTMPDH    := $(SPECTRUMPAINTERTMPDS:.cxx=.h)
SPECTRUMPAINTERTMP2DS   := $(MODDIRS)/G__Spectrum2PainterTmp2.cxx
SPECTRUMPAINTERTMP2DO   := $(SPECTRUMPAINTERTMP2DS:.cxx=.o)
SPECTRUMPAINTERTMP2DH   := $(SPECTRUMPAINTERTMP2DS:.cxx=.h)

SPECTRUMPAINTERH  := $(filter-out $(MODDIRI)/LinkDef%,$(wildcard $(MODDIRI)/*.h))
SPECTRUMPAINTERS  := $(filter-out $(MODDIRS)/G__%,$(wildcard $(MODDIRS)/*.cxx))
SPECTRUMPAINTERO  := $(SPECTRUMPAINTERS:.cxx=.o)

SPECTRUMPAINTERDEP := $(SPECTRUMPAINTERO:.o=.d) $(SPECTRUMPAINTERDO:.o=.d)

#LF
SPECTRUMPAINTERTMPDEP  := $(SPECTRUMPAINTERTMPDO:.o=.d)

SPECTRUMPAINTERLIB := $(LPATH)/libSpectrumPainter.$(SOEXT)
SPECTRUMPAINTERMAP := $(SPECTRUMPAINTERLIB:.$(SOEXT)=.rootmap)

#LF
SPECTRUMPAINTERNM       := $(SPECTRUMPAINTERLIB:.$(SOEXT)=.nm)

# used in the main Makefile
ALLHDRS       += $(patsubst $(MODDIRI)/%.h,include/%.h,$(SPECTRUMPAINTERH))
ALLLIBS       += $(SPECTRUMPAINTERLIB)
ALLMAPS       += $(SPECTRUMPAINTERMAP)

# include all dependency files
INCLUDEFILES += $(SPECTRUMPAINTERDEP)

##### local rules #####
include/%.h:    $(SPECTRUMPAINTERDIRI)/%.h
		cp $< $@

#LF
$(SPECTRUMPAINTERLIB):   $(SPECTRUMPAINTERO) $(SPECTRUMPAINTERTMPDO) $(SPECTRUMPAINTERTMP2DO) $(SPECTRUMPAINTERDO) $(ORDER_) $(MAINLIBS) $(SPECTRUMPAINTERLIBDEP)
		@$(MAKELIB) $(PLATFORM) $(LD) "$(LDFLAGS)" \
		   "$(SOFLAGS)" libSpectrumPainter.$(SOEXT) $@ "$(SPECTRUMPAINTERO) $(SPECTRUMPAINTERTMPDO) $(SPECTRUMPAINTERTMP2DO) $(SPECTRUMPAINTERDO)" \
		   "$(SPECTRUMPAINTERLIBEXTRA)"

#LF
$(SPECTRUMPAINTERTMPDS):   $(SPECTRUMPAINTERH) $(SPECTRUMPAINTERL) $(ROOTCINTTMPEXE)
		@echo "Generating first dictionary $@..."
		$(ROOTCINTTMP) -f $@ -. 1 -c $(SPECTRUMPAINTERH) $(SPECTRUMPAINTERL)

#LF
$(SPECTRUMPAINTERTMP2DS):  $(SPECTRUMPAINTERH) $(SPECTRUMPAINTERL) $(ROOTCINTTMPEXE)
		@echo "Generating second dictionary $@..."
		$(ROOTCINTTMP) -f $@ -. 2 -c $(SPECTRUMPAINTERH) $(SPECTRUMPAINTERL)

#LF
$(SPECTRUMPAINTERDS):    $(SPECTRUMPAINTERH) $(SPECTRUMPAINTERL) $(ROOTCINTTMPEXE) $(SPECTRUMPAINTERNM)
		@echo "Generating third dictionary $@..."
		$(ROOTCINTTMP) -f $@ -L $(ROOTSYS)/$(SPECTRUMPAINTERNM) -. 3 -c $(SPECTRUMPAINTERH) $(SPECTRUMPAINTERL)

#LF
$(SPECTRUMPAINTERNM):      $(SPECTRUMPAINTERO) $(SPECTRUMPAINTERTMPDO) $(SPECTRUMPAINTERTMP2DO) 
		@echo "Generating symbols file $@..."
		nm -p --defined-only $(SPECTRUMPAINTERTMPDO) | awk '{printf("%s\n", $$3)'} > $(SPECTRUMPAINTERNM)
		nm -p --defined-only $(SPECTRUMPAINTERTMP2DO) | awk '{printf("%s\n", $$3)'} >> $(SPECTRUMPAINTERNM)
		nm -p --defined-only $(SPECTRUMPAINTERO) | awk '{printf("%s\n", $$3)'} >> $(SPECTRUMPAINTERNM)

$(SPECTRUMPAINTERMAP): $(RLIBMAP) $(MAKEFILEDEP) $(SPECTRUMPAINTERL)
		$(RLIBMAP) -o $(SPECTRUMPAINTERMAP) -l $(SPECTRUMPAINTERLIB) \
		   -d $(SPECTRUMPAINTERLIBDEPM) -c $(SPECTRUMPAINTERL)

all-spectrumpainter: $(SPECTRUMPAINTERLIB) $(SPECTRUMPAINTERMAP)

clean-spectrumpainter:
		@rm -f $(SPECTRUMPAINTERO) $(SPECTRUMPAINTERDO)

clean::         clean-spectrumpainter clean-pds-spectrumpainter

#LF
clean-pds-spectrumpainter:	
		rm -f $(SPECTRUMPAINTERTMPDS) $(SPECTRUMPAINTERTMPDO) $(SPECTRUMPAINTERTMPDH) \
		$(SPECTRUMPAINTERTMPDEP) $(SPECTRUMPAINTERTMP2DS) $(SPECTRUMPAINTERTMP2DO) $(SPECTRUMPAINTERTMP2DH) $(SPECTRUMPAINTERNM)

distclean-spectrumpainter: clean-spectrumpainter
		@rm -f $(SPECTRUMPAINTERDEP) $(SPECTRUMPAINTERDS) \
		   $(SPECTRUMPAINTERDH) $(SPECTRUMPAINTERLIB) $(SPECTRUMPAINTERMAP)

distclean::     distclean-spectrumpainter
