set(root_build_options)

#---------------------------------------------------------------------------------------------------
#---ROOT_BUILD_OPTION( name defvalue [description] )
#---------------------------------------------------------------------------------------------------
function(ROOT_BUILD_OPTION name defvalue)
  if(ARGN)
    set(description ${ARGN})
  else()
    set(description " ")
  endif()    
  option(${name} "${description}" ${defvalue})
  set(root_build_options ${root_build_options} ${name} PARENT_SCOPE )
endfunction()

function(ROOT_SHOW_OPTIONS)
  set(enabled)
  foreach(opt ${root_build_options})
    if(${opt})
      set(enabled "${enabled} ${opt}")
    endif()
  endforeach()
  message(STATUS "Enabled support for: ${enabled}")
endfunction()

ROOT_BUILD_OPTION(afs OFF "AFS support, requires AFS libs and objects")                 
ROOT_BUILD_OPTION(alien OFF "AliEn support, requires libgapiUI from ALICE")               
ROOT_BUILD_OPTION(asimage ON "Image processing support, requires libAfterImage")             
ROOT_BUILD_OPTION(astiff ON "Include tiff support in image processing")
ROOT_BUILD_OPTION(bonjour ON "Bonjour support, requires libdns_sd and/or Avahi")            
ROOT_BUILD_OPTION(builtin_afterimage ON "Built included libAfterImage, or use system libAfterImage")
ROOT_BUILD_OPTION(builtin_ftgl ON "Built included libFTGL, or use system libftgl")        
ROOT_BUILD_OPTION(builtin_freetype OFF "Built included libfreetype, or use system libfreetype")   
ROOT_BUILD_OPTION(builtin_glew ON "Built included libGLEW, or use system libGLEW")
ROOT_BUILD_OPTION(builtin_pcre ON "Built included libpcre, or use system libpcre")        
ROOT_BUILD_OPTION(builtin_zlib OFF "Built included libz, or use system libz")        
ROOT_BUILD_OPTION(castor ON "CASTOR support, requires libshift from CASTOR >= 1.5.2")             
ROOT_BUILD_OPTION(chirp ON "Chirp support (Condor remote I/O), requires libchirp_client")               
ROOT_BUILD_OPTION(cintex ON "Build the libCintex Reflex interface library")              
ROOT_BUILD_OPTION(clarens OFF "Clarens RPC support, optionally used by PROOF")            
ROOT_BUILD_OPTION(editline ON "Color-enabled prompt, requires (n)curses library")              
ROOT_BUILD_OPTION(dcache OFF "dCache support, requires libdcap from DESY")              
ROOT_BUILD_OPTION(exceptions ON "Turn on compiler exception handling capability")         
ROOT_BUILD_OPTION(explicitlink OFF "Explicitly link with all dependent libraries")      
ROOT_BUILD_OPTION(fftw3 OFF "Fast Fourier Transform support, requires libfftw3") 
ROOT_BUILD_OPTION(fitsio OFF "Read images and data from FITS files, requires cfitsio")                
ROOT_BUILD_OPTION(gviz OFF "Graphs visualization support, requires graphviz")                
ROOT_BUILD_OPTION(gdml OFF "GDML writer and reader")                
ROOT_BUILD_OPTION(genvector ON "Build the new libGenVector library" )            
ROOT_BUILD_OPTION(gfal OFF "GFAL support, requires libgfal")        
ROOT_BUILD_OPTION(glite OFF "gLite support, requires libglite-api-wrapper v.3 from GSI (https://subversion.gsi.de/trac/dgrid/wiki)")              
ROOT_BUILD_OPTION(globus OFF "Globus authentication support, requires Globus toolkit")              
ROOT_BUILD_OPTION(gsl_shared OFF "Enable linking against shared libraries for GSL (default no)")
ROOT_BUILD_OPTION(hdfs OFF "HDFS support; requires libhdfs from HDFS >= 0.19.1")         
ROOT_BUILD_OPTION(krb5 ON "Kerberos5 support, requires Kerberos libs")               
ROOT_BUILD_OPTION(ldap ON "LDAP support, requires (Open)LDAP libs")                
ROOT_BUILD_OPTION(mathmore OFF "Build the new libMathMore extended math library, requires GSL (vers. >= 1.8)")            
ROOT_BUILD_OPTION(memstat ON "A memory statistics utility, helps to detect memory leaks")    
ROOT_BUILD_OPTION(minuit2 OFF "Build the new libMinuit2 minimizer library")            
ROOT_BUILD_OPTION(monalisa OFF "Monalisa monitoring support, requires libapmoncpp")        
ROOT_BUILD_OPTION(mysql OFF "MySQL support, requires libmysqlclient")              
ROOT_BUILD_OPTION(odbc ON "ODBC support, requires libiodbc or libodbc")                
ROOT_BUILD_OPTION(opengl ON "OpenGL support, requires libGL and libGLU")              
ROOT_BUILD_OPTION(oracle OFF "Oracle support, requires libocci")              
ROOT_BUILD_OPTION(pch  OFF)   
ROOT_BUILD_OPTION(peac OFF "PEAC, PROOF Enabled Analysis Center, requires Clarens")       
ROOT_BUILD_OPTION(pgsql OFF "PostgreSQL support, requires libpq")               
ROOT_BUILD_OPTION(pythia6 OFF "Pythia6 EG support, requires libPythia6")            
ROOT_BUILD_OPTION(pythia8 OFF "Pythia8 EG support, requires libPythia8")             
ROOT_BUILD_OPTION(python ON "Python ROOT bindings, requires python >= 2.2")              
ROOT_BUILD_OPTION(qt OFF "Qt graphics backend, requires libqt >= 4.x")                
ROOT_BUILD_OPTION(qtgsi OFF "GSI's Qt integration, requires libqt >= 3")               
ROOT_BUILD_OPTION(reflex ON "Build the libReflex dictionary library")              
ROOT_BUILD_OPTION(roofit OFF "Build the libRooFit advanced fitting package")              
ROOT_BUILD_OPTION(ruby OFF "Ruby ROOT bindings, requires ruby >= 1.8")                
ROOT_BUILD_OPTION(rfio OFF "RFIO support, requires libshift from CASTOR >= 1.5.2")                
ROOT_BUILD_OPTION(rpath ON "Set run-time library load path on executables")              
ROOT_BUILD_OPTION(sapdb OFF "MaxDB/SapDB support, requires libsqlod and libsqlrte")              
ROOT_BUILD_OPTION(shadowpw OFF "Shadow password support")           
ROOT_BUILD_OPTION(shared ON "Use shared 3rd party libraries if possible")              
ROOT_BUILD_OPTION(soversion OFF "Set version number in sonames (recommended)")           
ROOT_BUILD_OPTION(srp OFF "SRP support, requires SRP source tree")       
ROOT_BUILD_OPTION(ssl ON "SSL encryption support, requires openssl")                
ROOT_BUILD_OPTION(table OFF "Build libTable contrib library")             
ROOT_BUILD_OPTION(tmva ON "Build TMVA multi variate analysis library")             
ROOT_BUILD_OPTION(unuran OFF "UNURAN - package for generating non-uniform random numbers")              
ROOT_BUILD_OPTION(winrtdebug OFF "Link against the Windows debug runtime library")         
ROOT_BUILD_OPTION(xft ON "Xft support (X11 antialiased fonts)")                
ROOT_BUILD_OPTION(xml ON "XML parser interface")
ROOT_BUILD_OPTION(x11 ON "X11 support")
ROOT_BUILD_OPTION(xrootd OFF "Build xrootd file server and its client (if supported)")
  
option(fail-on-missing "Fail the configure step if a required external package is missing" OFF)
option(minimal "Do not automatically search for support libraries" OFF)
option(gminimal "Do not automatically search for support libraries, but include X11" OFF)
  
              

