#!/bin/sh

#--- Help function -------------
printhelp()
{
   echo "   "
   echo "  pq2-info-server"
   echo "   "
   echo "  Purpose: show info about the datasets on a given server"
   echo "   "
   echo "  Syntax:"
   echo "           pq2-info-server [-h|--help] [-v] [-k] (-s servers|--server=servers)"
   echo "                           [-t tmpdir|--tmp=tmpdir] [-u serviceurl|--url=serviceurl]"
   echo "   "
   echo "   -h | --help   Print this help"
   echo "   -v            Verbose mode"
   echo "   -k            Keep temporary files"
   echo "   servers:      Comma-separated list of servers for which the information is wanted"
   echo "   serviceurl:   URL of the PROOF master or data server providing the information;"
   echo "                 for data servers, it must include the directory."
   echo "                 Can be specified via the envs PQ2PROOFURL or PQ2DSSRVURL."
   echo "   tmpdir        Directory for temporary files [/tmp/<user>]."
   echo "   "
}

PQ2=`which pq2 2> /dev/null`
if test "x$PQ2" = "x" ; then
   echo "Unknown command 'pq2'"
   exit 1
fi

DBGOPT=""
KEEPOPT=""
SRVURL=""
SERVER=""
TDIR=$TMPDIR
while getopts -:s:t:u:hkv i ; do
   case $i in
     h) printhelp ; exit ;;
     k) KEEPOPT="-k" ;;
     s) SERVER="-s $OPTARG" ;;
     t) TDIR="$OPTARG" ;;
     u) SRVURL="-u $OPTARG" ;;
     v) DBGOPT="-v" ;;
     -) case "$OPTARG" in
          *=*) oarg=`echo "$OPTARG" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
          *) oarg= ;;
        esac ;
        case $OPTARG in
          help)      printhelp ; exit ;;
          keep)      KEEPOPT="-k" ;;
          server=*)  SERVER="-s $oarg" ;;
          tmp=*)     TDIR="$oarg" ;;
          url=*)     SRVURL="-u $oarg" ;;
        esac
        ;;
     \?) printhelp; exit 1 ;;
  esac
done
if test "x$SERVER" = "x"; then
   echo "Some arguments are missing (s:$SERVER)!"
   printhelp
   exit
fi

# Run
export TMPDIR="$TDIR"; $PQ2 info-server $DBGOPT $KEEPOPT $SERVER $SRVURL
