#ifndef ROOT_RVersion
#define ROOT_RVersion

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if ROOT_VERSION_CODE >= ROOT_VERSION(2,23,4)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define ROOT_RELEASE "5.26/00b-proof"
#define ROOT_RELEASE_DATE "Apr 13 2010"
#define ROOT_RELEASE_TIME "00:00:56"
#define ROOT_SVN_REVISION 32288
#define ROOT_SVN_BRANCH "branches/dev/proof/branches/v5-26-00b-proof"
#define ROOT_VERSION_CODE 334435
#define ROOT_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#endif
