#!/bin/sh

#--- Help function -------------
printhelp()
{
   echo "   "
   echo "  pq2-cache"
   echo "   "
   echo "  Purpose: display or clear the local cache content"
   echo "   "
   echo "  Syntax:"
   echo "           pq2-cache -a show|clear [-h|--help] [-v] [-k]"
   echo "                     [-d datasets|--dataset=datasets] [-t tmpdir|--tmp=tmpdir]"
   echo "                     [-t tmpdir|--tmp=tmpdir] [-u serviceurl|--url=serviceurl]"
   echo "   "
   echo "   show          Display cache content"
   echo "   clear         Clear cache content"
   echo "   -h | --help   Print this help"
   echo "   -v            Verbose mode"
   echo "   -k            Keep temporary files"
   echo "   datasets      Datasets to processed; wildcards are supported"
   echo "   serviceurl:   URL of the PROOF master or data server providing the information;"
   echo "                 for data servers, it must include the directory."
   echo "                 Can be specified via the envs PQ2PROOFURL or PQ2DSSRVURL."
   echo "   tmpdir        Directory for temporary files [/tmp/<user>]."
   echo "   "
}

PQ2=`which pq2 2> /dev/null`
if test "x$PQ2" = "x" ; then
   echo "Unknown command 'pq2'"
   exit 1
fi

DBGOPT=""
DSNARG=""
KEEPOPT=""
SRVURL=""
TDIR=$TMPDIR
while getopts -:a:d:u:hkv i ; do
   case $i in
     a) ACTION="-o $OPTARG" ;;
     d) DSNARG="-d $OPTARG" ;;
     h) printhelp ; exit ;;
     k) KEEPOPT="-k" ;;
     t) TDIR="$OPTARG" ;;
     u) SRVURL="-u $OPTARG" ;;
     v) DBGOPT="-v" ;;
     -) case "$OPTARG" in
          *=*) oarg=`echo "$OPTARG" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
          *) oarg= ;;
        esac ;
        case $OPTARG in
          dataset=*) DSNARG="-d $oarg" ;;
          help)      printhelp ; exit ;;
          keep)      KEEPOPT="-k" ;;
          tmp=*)     TDIR="$oarg" ;;
          url=*)     SRVURL="-u $oarg" ;;
        esac
        ;;
     \?) printhelp; exit 1 ;;
  esac
done
# Fill empty fileds with any non-prefixed argument
eval next_arg=\$$OPTIND
echo "next_arg= $next_arg (OPTIND= $OPTIND)"
if test ! "x$next_arg" = "x" ; then
   if test "x$ACTION" = "x" ; then
      ACTION="-o $next_arg"
   fi
fi

# Run
export TMPDIR="$TDIR"; $PQ2 cache $ACTION $DBGOPT $KEEPOPT $DSNARG $SRVURL



