##===- cling/lib/EditLine/Makefile--------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
#  This implements the a C++ interpreter backend.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../../..
LIBRARYNAME := clingEditLine
BUILD_ARCHIVE = 1
CXXFLAGS = -fno-rtti

# Don't install Cling libraries
NO_INSTALL = 1

include $(LEVEL)/Makefile.common

