ADD_ENUMCONST(kModShift, = 0x01),
ADD_ENUMCONST(kModCtrl, = 0x02),
ADD_ENUMCONST(kModAlt, = 0x04),
ADD_ENUMCONST(kModCapsLock, = 0x10),
ADD_ENUMCONST(kModNumLock, = 0x20),
ADD_ENUMCONST(kModScrollLock, = 0x40),
ADD_ENUMCONST(kModDown, = 0x100),
ADD_ENUMCONST(kModUp, = 0x200),
ADD_ENUMCONST(kModRepeated, = 0x400) // e.g. key pressed repitition), double click), etc
